### ISSUE TITLE
Passing None to weight

### ISSUE THREAD

**Issue by jamesrkg** [Crunch-io/crunch-cube#172]
Based on this conversation:

https://crunch-io.slack.com/archives/CE5RYNQMR/p1548281042002700

Passing `weight=None` returns a cube weighted using the "active weight". This is very unexpected since in almost all cases what you're really asking for is an _unweighted_ cube. The only way to force the return of an unweighted cube is to use `weight=''` which is a bit hacky.

It's not completely clear to me what the result of that conversation was - is this a problem for whaam? The behavior still persists here regardless.

This problem may have been superseded by recent changes to the lib (I am not up to date on those). If so a little discussion here related to that would be helpful for future reference.

**Comment by jamesrkg** [comment]
@slobodan-ilic can you comment on this one for us please? 🙏

**Comment by alextanski** [comment]
Closing this.
